EALIEST_DATE='20080101'
STOCK_IPO_YEARS = 1 # 至少上市1年的股票
CONF_PATH = "conf/config.yml"
RESERVED_PERIODS = 50 # 预留50周的数据,目前看到的需要最长预留的是MACD:35，但是中间有各种假期、节日啥的，所以，预留40不够，改到50了
CODE_DATE = ['ts_code','trade_date'] # 定义一个最常用的取得数据集的 ts_code和 trade_date 的列名
TARGET = ['target']
TRAIN_TEST_SPLIT_DATE = '20190101' # 用来分割Train和Test的日期
BASELINE_INDEX_CODE = "000300.SH" # 用于计算对比用的基准指数代码，目前是沪深300
TOP_30 = 30
RISK_FREE_ANNUALLY_RETRUN = 0.03 # 在我国无风险收益率一般取值十年期国债收益，我查了一下有波动，取个大致的均值3%